Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2018-11, with the labels that each got.

#130 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.38
  pom.xml
Labels: updatebot

#132 update org.activiti.dependencies:activiti-dependencies to 7.0.52
  pom.xml
Labels: updatebot

#134 update org.activiti.dependencies:activiti-dependencies to 7.0.53
  pom.xml
Labels: updatebot

#135 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#137 update org.activiti.dependencies:activiti-dependencies to 7.0.54
  pom.xml
Labels: updatebot

#141 update org.activiti.dependencies:activiti-dependencies to 7.0.56
  pom.xml
Labels: updatebot

#142 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.41
  pom.xml
Labels: updatebot

#147 fix: Rename REST endpoint to resume a suspended process
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImplIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/cmdendpoint/CommandEndPointITStreamHandler.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/cmdendpoint/CommandEndpointIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/helper/ProcessInstanceRestTemplate.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessInstanceIT.java
Labels: enhancement

#146 feat: Add admin suspend process endpoint
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceAdminController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceAdminControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceAdminControllerImplIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessInstanceIT.java
Labels: enhancement

#154 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement

#155 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.47
  pom.xml
Labels: updatebot

#153 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.36
  pom.xml
Labels: updatebot

#152 update org.activiti.dependencies:activiti-dependencies to 7.0.61
  pom.xml
Labels: updatebot

#156 update org.activiti.dependencies:activiti-dependencies to 7.0.62
  pom.xml
Labels: updatebot

#158 update org.activiti.dependencies:activiti-dependencies to 7.0.63
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/Application.java
  pom.xml
Labels: updatebot

#157 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: enhancement, updatebot

#160 update org.activiti.dependencies:activiti-dependencies to 7.0.64
  pom.xml
Labels: updatebot

#159 fix: add activiti-cloud-runtime-bundle-dependencies-tests module
  activiti-cloud-runtime-bundle-dependencies/pom.xml
  activiti-cloud-services-runtime-bundle/pom.xml
  activiti-cloud-starter-runtime-bundle/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement

#162 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: do-not-merge, updatebot

#164 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#165 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#167 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  Jenkinsfile
  pom.xml
Labels: updatebot

#168 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#169 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot
