Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2019-02, with the labels that each got.

#230 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#231 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#232 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#236 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#237 Move controller for admin delete variables to ProcessInstanceVariableAdminController
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceAdminController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceVariableAdminController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceAdminControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableAdminControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceAdminControllerImplIT.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableAdminControllerImplIT.java
Labels: ready-for-review

#241 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#242 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#244 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#245 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#248 2456 fix swagger payload
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/SwaggerConfig.java
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/SwaggerModels.java
Labels: do-not-merge

#250 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/helper/ProcessDefinitionRestTemplate.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/helper/TaskRestTemplate.java
  pom.xml
Labels: updatebot

#252 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#253 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#255 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#256 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#259 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot
