Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2019-04, with the labels that each got.

#289 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#290 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#291 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#294 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#298 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#300 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#296 feat: implement TaskController.saveTask Rest Api (#2677)
  .mergify.yml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/TaskController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/TaskControllerImplIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/helper/TaskRestTemplate.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TasksIT.java
Labels: enhancement

#299 fix: NPE in RabbitCloudConnectorsAutoConfiguration
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/RabbitCloudConnectorsAutoConfiguration.java
Labels: bug, wip
