Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2019-09, with the labels that each got.

#361 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/test/java/org/activiti/cloud/services/core/commands/StartProcessInstanceCmdExecutorTest.java
  pom.xml
Labels: updatebot

#364 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#365 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/conf/CloudConnectorsAutoConfigurationIT.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/test/java/org/activiti/cloud/services/core/utils/TestProcessEngineConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/configuration/CloudEventsAutoConfigurationIT.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableAdminControllerImplIT.java
  activiti-cloud-starter-runtime-bundle-it/src/test/java/org/activiti/cloud/starter/tests/jobexecutor/MultipleRbJobExecutorIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/EmbeddedSubProcessAuditIT.java
  pom.xml
Labels: updatebot

#368 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#369 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#370 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#367 feat: Add support for BPMN Message Rest Api
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceAdminController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceController.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceAdminControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceAdminControllerImplIT.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImplIT.java
Labels: enhancement, ready-for-review

#372 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#375 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#377 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#363 Support for setting task Date/Time variables
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/conf/ServicesRestAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskAdminControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskVariableAdminControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskVariableControllerImpl.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskVariablesPayloadDateHandler.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/TaskVariablesPayloadDateHandlerTest.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TaskVariableMappingIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TaskVariablesIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TasksIT.java
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/task-date-var-mapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/task-date-var-mapping.bpmn20.xml
Labels: ready-for-review

#379 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#380 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#381 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#382 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#383 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#384 fix(signal): updated tests for SIGNAL_RECEIVED with execution on process start
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/SignalAuditProducerIT.java
  pom.xml
Labels: bug

#387 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#389 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#391 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#390 fix(ACTIVITI-3875): replaced activitivi:isInterrupting with isInterrupting attribute
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/MessageAuditProducerIT.bpmn20.xml
Labels: bug

#392 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#393 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#394 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot
