Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2019-11, with the labels that each got.

#415 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#417 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#419 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#420 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#421 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#424 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#425 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#426 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#427 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#428 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#429 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#430 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#431 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#432 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#434 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#435 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#436 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#403 feat(build): Start test containers in parallel
  activiti-cloud-starter-runtime-bundle-it/pom.xml
  activiti-cloud-starter-runtime-bundle/pom.xml
Labels: enhancement

#437 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#416 feat(AAE-102): support cloud native Bpmn messages
  activiti-cloud-runtime-bundle-dependencies/pom.xml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/RabbitCloudConnectorsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/configuration/CloudEventsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/converter/ToCloudProcessRuntimeEventConverter.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/listeners/CloudMessageSubscriptionCancelledProducer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/listeners/ProcessEngineEventsAggregator.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/converter/ToCloudProcessRuntimeMessageEventsConverterTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/listeners/CloudMessageProducerTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-job-executor/src/main/java/org/activiti/cloud/services/job/executor/MessageBasedJobManagerAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-connector/pom.xml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-connector/src/main/java/org/activiti/cloud/services/message/connector/MessageConnectorConsumer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-connector/src/main/java/org/activiti/cloud/services/message/connector/channels/MessageConnectorChannels.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-connector/src/main/java/org/activiti/cloud/services/message/connector/config/MessageConnectorAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-connector/src/main/resources/META-INF/spring.factories
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-connector/src/main/resources/config/message-connector-channels.properties
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/pom.xml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/BpmnMessageEventMessageBuilderFactory.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/BpmnMessageReceivedEventMessageProducer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/BpmnMessageSentEventMessageProducer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/BpmnMessageWaitingEventMessageProducer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageEventPayloadMessageBuilderAppender.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageEventPayloadMessageHeaders.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageEventSubscriptionMessageHeaders.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageEventsPrincipalAuthenticationToken.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageSenderTransactionSynchronization.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageSubscriptionCancelledEventMessageProducer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageSubscriptionEventMessageBuilderFactory.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/MessageSubscriptionMessageBuilderAppender.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/ReceiveMessagePayloadMessageStreamListener.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/StartMessageDeployedEventMessageBuilderFactory.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/StartMessageDeployedEventMessageProducer.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/StartMessageDeploymentDefinitionMessageBuilderAppender.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/StartMessagePayloadMessageStreamListener.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/channels/MessageEventsChannels.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/java/org/activiti/cloud/services/message/events/config/MessageEventsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/resources/META-INF/spring.factories
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-message-events/src/main/resources/config/message-events-channels.properties
  activiti-cloud-services-runtime-bundle/pom.xml
  activiti-cloud-starter-message-connector/pom.xml
  activiti-cloud-starter-message-connector/src/test/java/org/activiti/cloud/starter/message/connector/ActivitiCloudStarterMessageConnectorTest.java
  activiti-cloud-starter-message-connector/src/test/resources/application.properties
  activiti-cloud-starter-runtime-bundle/pom.xml
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MessageEventsIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/EmbeddedSubProcessAuditIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/MessageAuditProducerIT.java
  activiti-cloud-starter-runtime-bundle/src/test/resources/application-test.properties
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.catchMessage.bpmn20.xml
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ThrowCatchMessageIT.bpmn
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ThrowStartBoundarySubprocessMessageIT.bpmn
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ThrowStartBoundaryTaskMessageIT.bpmn
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ThrowStartEventSubprocessMessageIT.bpmn
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ThrowStartEventSubprocessNonInterruptingMessageIT.bpmn
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ThrowStartIntermediateMessageIT.bpmn
  pom.xml
Labels: enhancement, ready-for-review

#438 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#439 fix(AAE102): added message payload variable mapping provider
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/behavior/CloudActivityBehaviorFactory.java
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiCloudEngineAutoConfiguration.java
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/SignalBehaviourConfigurer.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MessageEventsIT.java
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/catchmessagemapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/catchmessagemapping.bpmn20.xml
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/throwmessagemapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/throwmessagemapping.bpmn20.xml
Labels: bug

#441 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#442 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#443 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#444 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#445 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#446 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#447 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#448 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/IntegrationRequestSender.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationResultEventHandler.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/IntegrationRequestSenderTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationResultEventHandlerTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/converter/ToCloudProcessRuntimeEventConverter.java
  pom.xml
Labels: updatebot

#449 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#450 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#320 AAE-771 Test updated to check taskDefinitionKey
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
Labels: ready-for-review

#451 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot
