Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2019-07, with the labels that each got.

#324 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#326 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TasksIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/EmbeddedSubProcessAuditIT.java
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/activitySignalEventsInSubprocess.bpmn20.xml
  pom.xml
Labels: updatebot

#329 ACTIVITI-3415 Add MappingAwareActivityBehaviorFactory
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/behavior/CloudActivityBehaviorFactory.java
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/ActivitiCloudEngineAutoConfiguration.java
  activiti-cloud-starter-runtime-bundle/src/main/java/org/activiti/cloud/starter/rb/configuration/SignalBehaviourConfigurer.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
  pom.xml
Labels: do-not-merge

#334 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#333 feat: add async executor default properties configuration
  activiti-cloud-starter-runtime-bundle/src/main/resources/metadata.properties
Labels: enhancement

#335 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#336 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#332 fix: use Spring profiles to isolate async executor test configuration
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/JobExecutorIT.java
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/TimerAuditProducerIT.java
Labels: bug
