Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2019-01, with the labels that each got.

#200 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#201 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#76 Consume connector definitions in RB
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/pom.xml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/behavior/MQServiceTaskBehavior.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationResultEventHandler.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/CloudConnectorsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/IntegrationRequestSenderTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/behavior/MQServiceTaskBehaviorTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationResultEventHandlerTest.java
  pom.xml
Labels: enhancement

#209 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#210 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#211 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#214 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#215 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#223 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#226 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions
  pom.xml
Labels: updatebot

#224 Add @Conditional RabbitCloudConnectorsAutoConfiguration for SCS Rabbit Binder
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/pom.xml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/CloudConnectorsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/RabbitCloudConnectorsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/META-INF/spring.factories
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/pom.xml
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-subscriptions/pom.xml
  activiti-cloud-starter-runtime-bundle/pom.xml
Labels: bug

#203 Add event type routing key prefix for engine and integration context
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/message/IntegrationContextRoutingKeyResolver.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/message/IntegrationContextRoutingKeyResolverTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/message/AbstractMessageHeadersRoutingKeyResolver.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/message/AuditProducerRoutingKeyResolver.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/message/MessageBuilderAppenderChain.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/listeners/MessageProducerCommandContextCloseListenerTest.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/message/AuditProducerRoutingKeyResolverTest.java
Labels: enhancement, ready-for-review
