Repository Activiti/activiti-cloud-runtime-bundle-service, pull requests merged in 2020-01, with the labels that each got.

#475 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#476 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#478 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#479 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#477 fix(AAE-731): Removed routing-key-expression override
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/conf/activiti/services/connectors/RabbitCloudConnectorsAutoConfiguration.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/META-INF/spring.factories
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/config/integration-result-stream.properties
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/conf/CloudConnectorsAutoConfigurationIT.java
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/resources/META-INF/activiti-audit-producer.properties
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/configuration/CloudEventsAutoConfigurationIT.java
Labels: bug

#480 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#481 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#482 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#483 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#484 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#485 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#486 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#487 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#490 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#491 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#492 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/pom.xml
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskIT.java
  pom.xml
Labels: updatebot

#494 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#495 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/TasksIT.java
  pom.xml
Labels: updatebot

#497 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#499 fix: Extracted external dependencies to root pom dependency management
  activiti-cloud-runtime-bundle-dependencies/pom.xml
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
  pom.xml
Labels: enhancement

#500 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#501 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#502 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#503 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#505 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#506 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#507 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#508 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  pom.xml
Labels: updatebot

#509 fix(versions): update Activiti/activiti-cloud-runtime-bundle-service versions into develop
  activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MQServiceTaskIT.java
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/catchmessagemapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/constants-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/process-with-service-task-not-first-step-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/processWithExtensionVariables-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/task-date-var-mapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/task-variable-mapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/throwmessagemapping-extensions.json
  activiti-cloud-starter-runtime-bundle/src/test/resources/processes/variable-mapping-extensions.json
  pom.xml
Labels: updatebot
